apiVersion: v1
kind: Secret
metadata:
  name: shop-postgres-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app: shop-postgres
    owner: {{ .Values.global.owner }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.user | quote }}
  password: {{ .Values.postgres.password | quote }}