apiVersion: v1
kind: Service
metadata:
  name: n8n-external
  namespace: monitoring
  labels:
    app: n8n-external
spec:
  ports:
    - port: 5678
      targetPort: 5678
      name: metrics
---
apiVersion: v1
kind: Endpoints
metadata:
  name: n8n-external
  namespace: monitoring
  labels:
    app: n8n-external
subsets:
  - addresses:
      - ip: 0.250.250.254
    ports:
      - port: 5678
        name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: n8n-monitor
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  selector:
    matchLabels:
      app: n8n-external
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
