apiVersion: v1
kind: Pod
metadata:
  name: violation-no-resources
  namespace: default
  labels:
    app: violation-test
    owner: gopher-hunter
spec:
  containers:
    - name: nginx
      image: nginx:1.27
