alertmanager:
  alertmanagerSpec:
    configSecret: alertmanager-kube-prom-kube-prometheus-alertmanager

  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: webhook-receiver
      group_by: ["alertname", "severity"]
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 1h

      routes:
        - matchers:
            - severity = "critical"
          receiver: webhook-receiver
          group_wait: 10s
          repeat_interval: 5m

        - matchers:
            - alertname = "Watchdog"
          receiver: "null"

    receivers:
      - name: webhook-receiver
        webhook_configs:
          - url: "http://webhook-echo.monitoring.svc.cluster.local/"
            send_resolved: true

      - name: "null"
