{
 "title": "RED — api-service",
 "tags": [
  "api-service",
  "red"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS - интенсивность запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"api-service\", path!=\"/metrics\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Доля ошибок 5xx (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"api-service\", path!=\"/metrics\", status=~\"5..\"}[1m])) / sum(rate(http_requests_total{job=\"api-service\", path!=\"/metrics\"}[1m])) * 100",
     "legendFormat": "5xx %"
    }
   ]
  },
  {
   "title": "Время ответа p95 (сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"api-service\", path!=\"/metrics\"}[5m])))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}